volumes:
  data:

services:
  db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: tasker-db
      POSTGRES_PASSWORD: tasker
      POSTGRES_USER: tasker
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5000:5432

  angular-app:
    build:
      context: apps/tasker-client
      args:
        MODE: dev
      tags:
        - tasker-frontend:latest
    depends_on:
      - spring-app
    ports:
      - 4200:80

  spring-app:
    build:
      context: apps/tasker-api
      tags:
        - tasker-backend:latest
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tasker-db
      SPRING_DATASOURCE_USERNAME: tasker
      SPRING_DATASOURCE_PASSWORD: tasker
    ports:
      - 8080:8080
