services:
  spring-app:
    build:
      context: apps/tasker-api
      tags:
        - tasker-backend:latest
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:4500/tasker
    restart: always
    ports:
      - 8080:8080

  postgres-db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: tasker
      POSTGRES_PASSWORD: user
      POSTGRES_USER: user
    ports:
      - 4500:5432

  angular-app:
    build:
      context: apps/tasker-client
      args:
        MODE: dev
      tags:
        - tasker-frontend:latest
    depends_on:
      - spring-app
    ports:
      - 4200:80
