spring:
  datasource:
    url: jdbc:postgresql://localhost:4500/tasker
    password: user
    username: user
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/ui
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  private:
    key: file:./private.pem
  public:
    key: file:./public.pem

server:
  servlet:
    context-path: /api/v1
  error:
    include-stacktrace: never
