spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/task_manager_db
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs.html
  default-consumes-media-type: application/json 
  default-produces-media-type: application/json
