spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/task_manager_db
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/ui
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  private:
    key: classpath:private.pem
  public:
    key: classpath:public.pem

server:
  servlet:
    context-path: /api/v1
  error:
    include-stacktrace: never
